/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecycleBinRouteImport } from './routes/recycle-bin'
import { Route as LearningViewerCourseIdModuleIdCurriculumIdRouteImport } from './routes/learning.viewer.$courseId.$moduleId.$curriculumId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecycleBinRoute = RecycleBinRouteImport.update({
  id: '/recycle-bin',
  path: '/recycle-bin',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningViewerCourseIdModuleIdCurriculumIdRoute =
  LearningViewerCourseIdModuleIdCurriculumIdRouteImport.update({
    id: '/learning/viewer/$courseId/$moduleId/$curriculumId',
    path: '/learning/viewer/$courseId/$moduleId/$curriculumId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recycle-bin': typeof RecycleBinRoute
  '/learning/viewer/$courseId/$moduleId/$curriculumId': typeof LearningViewerCourseIdModuleIdCurriculumIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recycle-bin': typeof RecycleBinRoute
  '/learning/viewer/$courseId/$moduleId/$curriculumId': typeof LearningViewerCourseIdModuleIdCurriculumIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/recycle-bin': typeof RecycleBinRoute
  '/learning/viewer/$courseId/$moduleId/$curriculumId': typeof LearningViewerCourseIdModuleIdCurriculumIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/recycle-bin' | '/learning/viewer/$courseId/$moduleId/$curriculumId'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/recycle-bin' | '/learning/viewer/$courseId/$moduleId/$curriculumId'
  id:
    | '__root__'
    | '/'
    | '/recycle-bin'
    | '/learning/viewer/$courseId/$moduleId/$curriculumId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecycleBinRoute: typeof RecycleBinRoute
  LearningViewerCourseIdModuleIdCurriculumIdRoute: typeof LearningViewerCourseIdModuleIdCurriculumIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recycle-bin': {
      id: '/recycle-bin'
      path: '/recycle-bin'
      fullPath: '/recycle-bin'
      preLoaderRoute: typeof RecycleBinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/viewer/$courseId/$moduleId/$curriculumId': {
      id: '/learning/viewer/$courseId/$moduleId/$curriculumId'
      path: '/learning/viewer/$courseId/$moduleId/$curriculumId'
      fullPath: '/learning/viewer/$courseId/$moduleId/$curriculumId'
      preLoaderRoute: typeof LearningViewerCourseIdModuleIdCurriculumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecycleBinRoute: RecycleBinRoute,
  LearningViewerCourseIdModuleIdCurriculumIdRoute:
    LearningViewerCourseIdModuleIdCurriculumIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
